-- MySQL Script generated by MySQL Workbench
-- Sat Jun  6 16:40:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema domingoooo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema domingoooo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `domingoooo` DEFAULT CHARACTER SET latin1 ;
USE `domingoooo` ;

-- -----------------------------------------------------
-- Table `domingoooo`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingoooo`.`pelicula` (
  `idPelicula` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(20) NOT NULL,
  `Imagen` LONGBLOB NOT NULL,
  `Duracion` VARCHAR(10) NOT NULL,
  `Genero` VARCHAR(10) NOT NULL,
  `Clasificacion` VARCHAR(10) NOT NULL,
  `Sinopsis` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPelicula`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `domingoooo`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingoooo`.`serie` (
  `idSerie` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Temporada` INT(11) NOT NULL,
  `Capitulo` INT(11) NOT NULL,
  `Genero` VARCHAR(20) NOT NULL,
  `Clasificacion` VARCHAR(10) NOT NULL,
  `sinopsis` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `domingoooo`.`contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingoooo`.`contenido` (
  `idContenido` INT(11) NOT NULL AUTO_INCREMENT,
  `Clasificacion` VARCHAR(10) NOT NULL,
  `idPelicula` INT NOT NULL,
  `idSerie` INT NOT NULL,
  PRIMARY KEY (`idContenido`),
  INDEX `fk_contenido_pelicula1_idx` (`idPelicula` ASC) VISIBLE,
  INDEX `fk_contenido_serie1_idx` (`idSerie` ASC) VISIBLE,
  CONSTRAINT `fk_contenido_pelicula1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `domingoooo`.`pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenido_serie1`
    FOREIGN KEY (`idSerie`)
    REFERENCES `domingoooo`.`serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `domingoooo`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingoooo`.`cuenta` (
  `correo` VARCHAR(20) NOT NULL,
  `tarjeta` BIGINT(20) NOT NULL,
  `fechaEx` DATE NOT NULL,
  `contrasenia` VARCHAR(10) NULL DEFAULT NULL,
  `idCuenta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `domingoooo`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingoooo`.`perfil` (
  `idPerfil` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `idioma` VARCHAR(20) NOT NULL,
  `foto` VARCHAR(30) NOT NULL,
  `idCuenta` INT(11) NOT NULL,
  `idContenido` INT(11) NOT NULL,
  PRIMARY KEY (`idPerfil`),
  INDEX `fk_perfil_cuenta_idx` (`idCuenta` ASC) VISIBLE,
  INDEX `fk_perfil_contenido1_idx` (`idContenido` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `domingoooo`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_cuenta`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `domingoooo`.`cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
