-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 11:14:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema domingo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema domingo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `domingo` DEFAULT CHARACTER SET latin1 ;
USE `domingo` ;

-- -----------------------------------------------------
-- Table `domingo`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingo`.`cuenta` (
  `correo` VARCHAR(20) NOT NULL,
  `tarjeta` BIGINT(20) NOT NULL,
  `fechaEx` DATE NOT NULL,
  `contraseña` VARCHAR(10) NOT NULL,
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `domingo`.`contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingo`.`contenido` (
  `idContenido` INT NOT NULL AUTO_INCREMENT,
  `Clasificacion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idContenido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domingo`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingo`.`pelicula` (
  `idPelicula` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Clasificacion` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `idContenido` INT NOT NULL,
  `Duracion` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(20) NOT NULL,
  `Clasificacion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idPelicula`),
  INDEX `fk_pelicula_contenido1_idx` (`idContenido` ASC) VISIBLE,
  CONSTRAINT `fk_pelicula_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `domingo`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `domingo`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingo`.`perfil` (
  `idPerfil` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `idioma` VARCHAR(20) NOT NULL,
  `foto` VARCHAR(30) NOT NULL,
  `idCuenta` INT NOT NULL,
  `idContenido` INT NOT NULL,
  PRIMARY KEY (`idPerfil`),
  INDEX `fk_perfil_cuenta_idx` (`idCuenta` ASC) VISIBLE,
  INDEX `fk_perfil_contenido1_idx` (`idContenido` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_cuenta`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `domingo`.`cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `domingo`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `domingo`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domingo`.`serie` (
  `idSerie` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Clasificacion` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `idContenido` INT NOT NULL,
  `Temporada` INT NOT NULL,
  `Capitulo` INT NOT NULL,
  `Genero` VARCHAR(20) NOT NULL,
  `Clasificacion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idSerie`),
  INDEX `fk_serie_contenido1_idx` (`idContenido` ASC) VISIBLE,
  CONSTRAINT `fk_serie_contenido1`
    FOREIGN KEY (`idContenido`)
    REFERENCES `domingo`.`contenido` (`idContenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
